# Generated by Django 3.1.7 on 2021-03-18 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('origin', models.CharField(max_length=70)),
                ('destiny', models.CharField(max_length=70)),
                ('allocated_vehicles', models.IntegerField()),
                ('travel_time', models.CharField(max_length=9)),
                ('stops', models.IntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('max_speed', models.IntegerField()),
                ('max_passengers', models.IntegerField()),
                ('next_maintenance', models.DateField()),
                ('driver', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('base_price', models.FloatField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no sistema')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.route')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_birthday', models.DateField()),
                ('passenger_cpf', models.CharField(max_length=11)),
                ('payment_method', models.CharField(max_length=50)),
                ('change_price', models.FloatField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no sistema')),
                ('passenger_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.travel')),
            ],
        ),
    ]
