# Generated by Django 3.1.7 on 2021-03-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='arrival',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='travel',
            name='departure',
            field=models.CharField(max_length=9),
        ),
    ]
