# Generated by Django 3.1.7 on 2021-03-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0003_remove_route_travel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
